services:
  - type: web
    name: matrix-backend
    runtime: python
    plan: free
    envVars:
      - key: API_TOKEN
        sync: false
      - key: CORS_ORIGINS
        value: https://your-frontend.vercel.app
      - key: STATE_FILE
        value: /data/state.json
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
